plugins {
    id 'com.android.application'
}

android {
    namespace 'com.narmanb.ikemeninstaller'
    compileSdk 35

    defaultConfig {
        applicationId 'com.narmanb.ikemeninstaller'
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName '1.8.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'com.github.junrar:junrar:8.1.0'
    implementation 'org.apache.commons:commons-compress:1.27.1'
    implementation 'org.tukaani:xz:1.10'
    implementation 'org.slf4j:slf4j-nop:2.0.17'
}
